# Generated by Django 4.0 on 2024-02-14 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_table',
            name='request_to_date',
        ),
    ]
