# Generated by Django 4.0 on 2024-04-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='addnpic',
            field=models.ImageField(blank=True, null=True, upload_to='post_photos/'),
        ),
        migrations.AddField(
            model_name='post',
            name='addnpic1',
            field=models.ImageField(blank=True, null=True, upload_to='post_photos/'),
        ),
        migrations.AddField(
            model_name='post',
            name='addnpic2',
            field=models.ImageField(blank=True, null=True, upload_to='post_photos/'),
        ),
        migrations.AddField(
            model_name='post',
            name='update1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='update2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
