# Generated by Django 4.0 on 2024-02-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_request_table_request_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_table',
            name='request_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
