# Generated by Django 4.0 on 2024-05-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_customuser_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='action_icons/'),
        ),
    ]
