# Generated by Django 4.0 on 2024-02-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
                ('request_type', models.CharField(max_length=100)),
                ('transction_id', models.IntegerField()),
                ('order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=200)),
                ('payment_mode', models.CharField(max_length=100)),
                ('gateway', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customuser')),
            ],
        ),
    ]
