# Generated by Django 4.0 on 2024-02-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_post_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='adhaar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
