# Generated by Django 4.0 on 2024-02-27 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customuser_adhaar'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='amount',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='action',
            name='order_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customuser'),
        ),
        migrations.AlterField(
            model_name='transctions',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transctions',
            name='gateway',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transctions',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transctions',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transctions',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transctions',
            name='transction_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
