# Generated by Django 4.0 on 2024-02-27 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_action_amount_alter_action_order_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transctions',
            name='for_action',
            field=models.ForeignKey(default='blank', on_delete=django.db.models.deletion.CASCADE, to='main.action'),
        ),
        migrations.AddField(
            model_name='transctions',
            name='status',
            field=models.CharField(default='blank', max_length=100),
        ),
    ]
