# Generated by Django 4.0 on 2024-02-27 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_transctions_for_action_transctions_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transctions',
            name='for_action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.action'),
        ),
        migrations.AlterField(
            model_name='transctions',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
